-- AlterTable
ALTER TABLE "player" ALTER COLUMN "position" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "birthDate" DROP NOT NULL,
ALTER COLUMN "photo_path" DROP NOT NULL,
ALTER COLUMN "dominate_color" DROP NOT NULL;

-- AlterTable
ALTER TABLE "team" ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "flag_path" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "world_rating" DROP NOT NULL,
ALTER COLUMN "earned" DROP NOT NULL,
ALTER COLUMN "logo_path" DROP NOT NULL,
ALTER COLUMN "dominate_color" DROP NOT NULL;
